### ISSUE TITLE
Publish on pip

### ISSUE THREAD

**Issue by ben-manes** [tchar/pushbots#1]
It would be really nice to pip install this library rather than copying it into a project.

**Comment by tchar** [comment]
Hello. Sorry for the delay, but I was having some exams/studying.
As requested I have uploaded this to [PyPi](https://pypi.python.org/pypi/pushbots/0.0.1) and you can install it by typing:
pip install pushbots.
More info: [README:Install](https://github.com/tchar/pushbots#install)
